---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-testing-3
  namespace: servicex-testing-3
spec:
  interval: 1m
  serviceAccountName: servicex-testing-3
  chart:
    spec:
      chart: servicex
      version: '1.0.12'
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
        namespace: servicex-testing-3
      interval: 1m
