---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - servicex-repository.yaml
  - servicex-release.yaml
  - servicex-prod-2-sealed-secrets.yaml
  - values.yaml

secretGenerator:
  - name: servicex-secrets
    namespace: servicex-prod-2
    type: Opaque

configurations:
  - kustomizeconfig.yaml
