---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: servicex-kustomization
  namespace: servicex-uproot
resources:
  - servicex-repository.yaml
  - servicex-release.yaml
  - servicex-sealed-secret.yaml
    #- servicex-testing-1-sealed-slack.yaml
    #- servicex-testing-1-sealed-docker.yaml
    #- slack-notification.yaml
    #- docker-webhook.yaml
#configMapGenerator:
#  - name: servicex-values
#    files:
#      - values.yaml=values.yaml
#configurations:
#  - kustomizeconfig.yaml
