---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: servicex-testing-1-docker
  namespace: servicex-testing-1
spec:
  type: dockerhub
  secretRef:
    name: dockerhub-token
  resources:
    - kind: ImageRepository
      name: servicex-image-repo
