---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - servicex-repository.yaml
  - servicex-release.yaml
  - servicex-testing-1-sealed-secrets.yaml

secretGenerator:
  - name: servicex-secrets
    namespace: servicex-testing-1
    type: Opaque

resources:
  - values.yaml

configurations:
  - kustomizeconfig.yaml
