---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: servicex-testing-2-kustomization
  namespace: servicex-testing-2

resources:
  - servicex-repository.yaml
    #- servicex-release.yaml
  - servicex-testing-2-sealed-secret.yaml
  - servicex-testing-2-sealed-slack.yaml
  - values.yaml
  - slack-notification.yaml

secretGenerator:
  - name: servicex-secrets
    namespace: servicex-testing-2
    type: Opaque
  - name: servicex-slack
    namespace: servicex-testing-2
    type: Opaque

configurations:
  - kustomizeconfig.yaml
