apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: servicex-slack
  namespace: servicex-prod-xaod
spec:
  encryptedData:
    address: AgCLxAWloeeo8w6GH4VcxCFa4WxyM1Q7x/ScPKUBqvqkv+oD/1uEL7hjSwOlOSUx7cUW0r9B2MszkmSAszrDBPW026geIuoeDH2R3fjPuOBLhbdJrNYcuPacAedkBEkALw187bwRfbXstkHfzEEna5HX4QjbN1sczucLNf4h2uhWrSimpTEtCNn1YBWB1LUjdaVIwfk0YWp5Hdebn7MDlTNTOSZKhwyHTTu9cL/UEeYCyERp66udXLbK+LYJP3udchRhrrTZPKbEiAakuo96Zkc2rkZvtSVUqMkZHjdggs18lUiufEvsfSilNxg7aV7SyW9KRuTo5jYJCfdoPmLsm3YmDmGu+PPkXmLzdtOlRaDWghsGHi9hNPGraco6SC5cHW7eZ6QTAaaKEeOR2tfEA82QyIXtGicjgj/fFM6iKXqXck8wWQVwRoxcJJfTopDnKlj8k4rgSPaVIcZ7s4JVfsWLrAGRFH2tHBsEMzkkAdMPqHby2Mgjfj+GNLlcKjkQ2rdW6TBM2ZSCufmV3OJULIRGhGLyVRwVODSUa35E/16YwMQAeEIFVdfL5lqHnlyD6sqs1wmLZ7jkxIwC+dw5fCkMzqBDcoWhcc6y9s/NcZYyF8nNX0qHK1WC4GrCTDOp8TJ8fflaqjLsifALAl06Gcmr13InCA2wkk3sTLTFl7g3ohW/kno0WUBrNCOhkhQV3gmEENv1M+V97uNw6OQy44jZuJH0uqUPGDFmkaT92oP/aKQowFc+zUij5bYcX2XNijgQg0PLtFsvHB//JogLAP4RSpRvpfirlgJqRMwcFFqb
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: servicex-slack
      namespace: servicex-prod-xaod
    type: Opaque

