---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - servicex-repository.yaml
  - servicex-release.yaml
  - values.yaml
  - servicex-int-2-sealed-secret.yaml

secretGenerator:
  - name: servicex-secrets
    namespace: servicex-int-2
    type: Opaque

configurations:
  - kustomizeconfig.yaml
