---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: servicex-int-2-kustomization
  namespace: servicex-int-2

resources:
  - servicex-repository.yaml
    #- servicex-release.yaml
  - values.yaml
  - servicex-int-2-sealed-secret.yaml
  - servicex-int-2-sealed-slack.yaml
  - slack-notification.yaml

configurations:
  - kustomizeconfig.yaml
